USE mydb;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  flag BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS colors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

ALTER TABLE users
  ADD COLUMN favorite_color,
  ADD FOREIGN KEY (favorite_color) REFERENCE colors(id);
